### ISSUE TITLE
ipython is using python3

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#170]
pip installs `ipython3` and overwrites the `ipython` command. We need to reinstall `ipython2` afterwards to keep `ipython` and `python` commands the same python version.

**Comment by denisri** [comment]
When I reinstall ipython~=5.9.0 (same version as earlier), it breaks and I get the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ipython2", line 5, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/application.py", line 3, in <module>
    from .buffer import Buffer, AcceptAction
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/buffer.py", line 7, in <module>
    from .auto_suggest import AutoSuggest
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/auto_suggest.py", line 13, in <module>
    from .filters import to_cli_filter
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/filters/__init__.py", line 33, in <module>
    from .base import *
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/filters/base.py", line 5, in <module>
    from prompt_toolkit.utils import test_callable_args
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/utils.py", line 9, in <module>
    from wcwidth import wcwidth
  File "/usr/local/lib/python2.7/dist-packages/wcwidth/__init__.py", line 12, in <module>
    from .wcwidth import ZERO_WIDTH  # noqa
  File "/usr/local/lib/python2.7/dist-packages/wcwidth/wcwidth.py", line 79, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

Indeed the directory `/usr/lib/python2.7/dist-packages/backports` has completely disapeared from the system, whereas it is installed via apt and is still listed in `dpkg -L python-backports.functools-lru-cache`.
_Something_ did remove it from the system. I love pip, didn't I tell you ?...

**Comment by denisri** [comment]
`install -U --force-reinstall 'ipython~=5.9.0'` (as root) wipes away the system files in `/usr/lib/python2.7/dist-packages/backports` !!
Incredible, isn't it ?

**Comment by denisri** [comment]
Moreover the `backports` packages installed by pip in `/usr/local/lib/python2.7/dist-packages/backports` are not used:
```
>>> import backports
>>> backports.__path__
['/usr/lib/python2.7/dist-packages/backports']
```

**Comment by denisri** [comment]
I had to force reinstall backports via apt.
