### ISSUE TITLE
Using 'bv' without parameters crashes

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#186]
```shellsession
$ bin/bv
/casa/host/build/bin/python: No module named casa_distro
Traceback (most recent call last):
  File "bin/bv", line 147, in <module>
    subprocess.check_call(host_command)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/volatile/bv/cron/casa-distro/bin/casa_distro', 'run', 'base_directory=/volatile/bv/cron', 'bv_env_host', 'python', '-m', 'casa_distro.configuration_gui']' returned non-zero exit status 1
```

Maybe using `bv` without parameters should open a bash shell in the container? Or print some help message?

**Comment by ylep** [comment]
My bad, this is a problem with my setup (I do not have `casa-distro` installed in that container).
