### ISSUE TITLE
casa_distro documentation is not built because 

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#219]
Because of https://github.com/brainvisa/casa-distro/commit/848a9c538f705a62abbf5de3253f7e1c8ff292c5 the Sphinx documentation of casa-distro is broken, because that relies on running "casa_distro help" which now returns an error in the container.

```
Running Sphinx v1.6.7
the "casa_distro" command has been called from within a casa-distro container. This is not the way it should be used: it must be called from the host system.

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 719, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 292, in <module>
    help = subprocess.check_output(['casa_distro', 'help', 'format=rst', 'full=1'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['casa_distro', 'help', 'format=rst', 'full=1']' returned non-zero exit status 1
```

Maybe we could special-case "help" to allow running in the container...

**Comment by denisri** [comment]
Oh. Crap. Yes...

**Comment by denisri** [comment]
It should be fixed, can you try again please ?

**Comment by denisri** [comment]
Fixed.
