### ISSUE TITLE
all commands fail to start with nvidia-container-cli: initialization error: nvml error: driver not loaded

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#258]
This bug affects BrainVISA 5.0.1.

A workaround is to uninstall `nvidia-container-tools`.

```$ bv
nvidia-container-cli: initialization error: nvml error: driver not loaded
Traceback (most recent call last):
  File "/volatile/brainvisa/casa-distro/bin/casa_distro", line 34, in <module>
    main()
  File "/volatile/brainvisa/casa-distro/python/casa_distro/command.py", line 347, in main
    result = command(*args, **kwargs)
  File "/volatile/brainvisa/casa-distro/python/casa_distro/user_commands.py", line 742, in run
    verbose=verbose)
  File "/volatile/brainvisa/casa-distro/python/casa_distro/environment.py", line 791, in run_container
    verbose=verbose)
  File "/volatile/brainvisa/casa-distro/python/casa_distro/singularity.py", line 622, in run
    nv_binds = _nv_libs_binds()
  File "/volatile/brainvisa/casa-distro/python/casa_distro/singularity.py", line 459, in _nv_libs_binds
    '--libraries'], bufsize=-1)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['nvidia-container-cli', 'list', '--libraries']' returned non-zero exit status 1
```

```
$ nvidia-container-cli info
nvidia-container-cli: initialization error: nvml error: driver not loaded
```

**Comment by ylep** [comment]
@brainvisa/release  Given the seriousness of this issue (affected users cannot start any command) I have patched the live version at `/i2bm/brainvisa/brainvisa-cea-5.0.1/casa-distro/python/casa_distro/singularity.py`.

**Comment by denisri** [comment]
When does it occur ? When is the driver not loaded on host side ? (in other words: is it a problem that many users have ?)

**Comment by ylep** [comment]
I don't know exactly, it has occurred on a recent laptop installed by CEA, where I was connected over SSH. The `nvidia` packages installed on that machine are:

```shellsession
$ aptitude search 'nvidia~i'
i   libnvidia-cfg1-390              - NVIDIA binary OpenGL/GLX configuration lib
i A libnvidia-common-390            - Shared files used by the NVIDIA libraries
i   libnvidia-compute-390           - NVIDIA libcompute package
i A libnvidia-compute-390:i386      - NVIDIA libcompute package
i   libnvidia-container-tools       - NVIDIA container runtime library (command-
i A libnvidia-container1            - NVIDIA container runtime library
i   libnvidia-decode-390            - NVIDIA Video Decoding runtime libraries
i A libnvidia-decode-390:i386       - NVIDIA Video Decoding runtime libraries
i   libnvidia-encode-390            - NVENC Video Encoding runtime library
i A libnvidia-encode-390:i386       - NVENC Video Encoding runtime library
i   libnvidia-fbc1-390              - NVIDIA OpenGL-based Framebuffer Capture ru
i A libnvidia-fbc1-390:i386         - NVIDIA OpenGL-based Framebuffer Capture ru
i   libnvidia-gl-390                - NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries
i A libnvidia-gl-390:i386           - NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries
i   libnvidia-ifr1-390              - NVIDIA OpenGL-based Inband Frame Readback
i A libnvidia-ifr1-390:i386         - NVIDIA OpenGL-based Inband Frame Readback
i   nvidia-compute-utils-390        - NVIDIA compute utilities
i   nvidia-dkms-390                 - NVIDIA DKMS package
i   nvidia-driver-390               - NVIDIA driver metapackage
i A nvidia-kernel-common-390        - Shared files used with the kernel module
i A nvidia-kernel-source-390        - NVIDIA kernel source package
i A nvidia-prime                    - Tools to enable NVIDIA's Prime
i A nvidia-settings                 - Tool for configuring the NVIDIA graphics d
i   nvidia-utils-390                - NVIDIA driver support binaries
i   xserver-xorg-video-nvidia-390   - NVIDIA binary Xorg driver
```

I have been unable to reproduce the issue on another machine, so maybe this is not *so* critical that it would mandate a 5.0.2... I'd say we can wait and see if the issue occurs with other people.

**Comment by denisri** [comment]
I can't even find libnvidia-container-tools in ubuntu repositories, I don't know how they were installed. if I understand, the problem is nvidia tools being installed on machines without a nvidia chip... ?

**Comment by ylep** [comment]
No, that laptop *has* a nvidia chip. As for libnvidia-container-tools, I am using that script to install it from the NVidia repositories:

```shell
DIST=$(. /etc/os-release; echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | \
  sudo apt-key add -
curl -s -L https://nvidia.github.io/libnvidia-container/$DIST/libnvidia-container.list | \
  sudo tee /etc/apt/sources.list.d/libnvidia-container.list > /dev/null
sudo apt-get install -y libnvidia-container-tools
```

**Comment by denisri** [comment]
In this case I don't understand why it doesn't work: nvidia-container-cli should work, and is used on host side. If it is properly installed and nvidia hardware and drivers are OK, then it should not trigger an error ?
Anyway being robust to it is perfectly OK, I'm just trying to understand why some people ran into this situation...

**Comment by ylep** [comment]
> If it is properly installed and nvidia hardware and drivers are OK, then it should not trigger an error ?

I agree with you, I suspect that something is wrong with the setup of the driver. However, I cannot really test because I do not have physical access to the laptop. Anyway, the problem should only affect the few people who go through the manual and installation of libnvidia-container-tools...
