### ISSUE TITLE
Error axon-runprocess

### ISSUE THREAD

**Issue by rbregand** [brainvisa/casa-distro#277]
Hi, 

I just hear about the axon-runprocess way to use SPM. I typed this following line into casa distro bash **axon-runprocess --list-processes** but theses errors  appear 

```
Traceback (most recent call last):
  File "/casa/host/build/python/brainvisa/processes.py", line 4712, in getProcessInstance
    if (isinstance(processIdClassOrInstance, six.string_types) or hasattr(processIdClassOrInstance, 'readline')) and minfFormat(processIdClassOrInstance)[1] == minfHistory:
  File "/casa/host/build/python/soma/minf/api.py", line 118, in minfFormat
    opened_source_file = open(source, encoding='UTF-8')
FileNotFoundError: [Errno 2] No such file or directory: 'spm8_table_measures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/casa/host/build/bin/axon-runprocess", line 4, in <module>
    run_module('brainvisa.axon.runprocess')
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/casa/host/build/python/brainvisa/axon/runprocess.py", line 383, in <module>
    hide=options.hide_proc_attrib)
  File "/casa/host/build/python/brainvisa/axon/processinfo.py", line 192, in process_list_help
    processes.readProcdoc(pi.id)  # ensure doc is here
  File "/casa/host/build/python/brainvisa/processes.py", line 307, in readProcdoc
    proc = getProcessInstance(processId)
  File "/casa/host/build/python/brainvisa/processes.py", line 4721, in getProcessInstance
    result = result()
  File "/casa/host/build/python/brainvisa/processes.py", line 1499, in __init__
    Parameterized.__init__(self, self.signature.shallowCopy())
  File "/casa/host/build/python/brainvisa/processes.py", line 809, in __init__
    self.initialization()
  File "/casa/host/build/brainvisa/toolboxes/catidb/processes/create_table_measures.py", line 28, in initialization
    ProcessExecutionNode('spm8_table_measures', optional=1))
  File "/casa/host/build/python/brainvisa/processes.py", line 2563, in __init__
    process = getProcessInstance(process)
  File "/casa/host/build/python/brainvisa/processes.py", line 4719, in getProcessInstance
    + '": invalid identifier or process file: ' + repr(e))
KeyError: 'Could not get process "\'spm8_table_measures\'": invalid identifier or process file: FileNotFoundError(2, \'No such file or directory\')'
```
I tried to rebuild from scratch a new casa distro but the previous errors still occurs.

Howewer, the threshold commands from the online documentation seem to work nicely (https://brainvisa.info/axon/user_doc/axon_manual2.html#brainvisa-commandline).

Anyone else facing the same issue ? 
Any ideas to resolve it ? 

Image_version :  5.0.3
os : Linux Mint 20.1

Thanks for your help,
Rémy

**Comment by denisri** [comment]
I have other errors using axon-runprocess --list-processes, not the same as yours but still errors. Some are due to calling processes init codes without catching exceptions.
(so the ticket should rather be in axon)
