### ISSUE TITLE
brainvisa crashes using ubuntu 20.04 dev image

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#286]
**Describe the bug**

When using the Ubuntu 20.04 image `casa-dev-5.1-1.sif`, axon crashes almost every time I close an axon process window. Is it only with my build ?

**To Reproduce**

1. run brainvisa
2. open a process GUI, for instalce "viewers/view HTML file"
3. don't even run or enter any parameter
4. close the process winfow
5. segfault.

**Expected behavior**
no crash

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: master branch (5.1)
 - version of the casa-dev image: `casa-dev-5.1-1.sif`, `build_number: 1`

The stacktrace in gdb varies a bit from one run to another:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f9173127f4f in QWindow::destroy() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007f9173127f4f in QWindow::destroy() () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007f9173128a4c in QWindow::event(QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007f9173d4547c in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007f9173ce3a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007f9173ced0f0 in QApplication::notify(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f9171cf9bf6 in  ()
    at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#6  0x00007f917386893a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f917311a635 in QGuiApplicationPrivate::processCloseEvent(QWindowSystemInterfacePrivate::CloseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007f917311f132 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007f91730f935b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007f9169c3e32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#11 0x00007f9172b8817d in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f9172b88400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f9172b884a3 in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f91738c0565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f91738674db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f917386f246 in QCoreApplication::exec() ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
[...]
```

or another time, using the morphologist pipeline:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f6babc1e9f8 in QWindow::isTopLevel() const ()
   from /lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007f6babc1e9f8 in QWindow::isTopLevel() const ()
    at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007f6babc21968 in QWindowPrivate::maybeQuitOnLastWindowClosed() ()
    at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007f6babc25a61 in QWindow::event(QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007f6bac84247c in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007f6bac7e0a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f6bac7ea0f0 in QApplication::notify(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f6baa7f6bf6 in  ()
    at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#7  0x00007f6bac36593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f6babc17635 in QGuiApplicationPrivate::processCloseEvent(QWindowSystemInterfacePrivate::CloseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007f6babc1c132 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007f6babbf635b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#11 0x00007f6ba273b32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#12 0x00007f6bab68517d in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f6bab685400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f6bab6854a3 in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f6bac3bd565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f6bac3644db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f6bac36c246 in QCoreApplication::exec() ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
[...]
```

**Comment by denisri** [comment]
Using sip 4.19.15 and PyQt 5.12.1 (built manually) exactly as we have done in Ubuntu 18.04 does not solve this problem.

**Comment by denisri** [comment]
I could build a run image based on the prerelease of Ubuntu 22.04, and using it start brainvisa (from an ubuntu 20.04 build, but not using compiled things), and in this image, I don't experience the crashes when closing axon process windows.
I suppose #289 still exists in Ubuntu 22.04 because it is present in the latest sip, but at least for this crash problem I wonder if we should not skip ubuntu 20 and just jump to 22... ?

**Comment by denisri** [comment]
Images 5.1 (ubuntu 20.04) have moved to 5.2 because of the numerous issues with this system - 5.1 will become a python3 variant of 5.0 (ubuntu 18.04). Thus this ticket now concerns images 5.2.

**Comment by denisri** [comment]
5.2 images have been dropped in favour of 5.3.
