### ISSUE TITLE
sip problems in casa-dev-5.2

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#289]
**Describe the bug**
PyAnatomist windows crash because they have a wrong reference count

**To Reproduce**
```
import anatomist.api as ana
a = ana.Anatomist()
w = a.createWindow('3D')
print(w.internalRep.__refcount__())
Out[1]: 42158497
```

**Expected behavior**
Using casa-dev-5.0, the output is `2`

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: master branch (5.1)
 - version of the casa-dev image: `casa-dev-5.1-1`, `build_number: 1`

**Additional context**
Is it a problem in sip and python bindings to reference counters ?
However in PyAims, refcounts to Volumes for instance seem OK. We have to investigate further.

**Comment by denisri** [comment]
After investigating a deal, I think it's a problem in sip 4.19.21 shipped in Ubuntu 20.04.
in Anatomist we have a rather complex inheritance tree where `AWindow3D` inherits (indirectly) `QMainWindow` and `RCObject`. Thus the address of the `RCObject` and `AWindow3D` parts in the C++ objects are not the same.. If we print the address of `this` in a bound method of `AWindow3D` (using `%MethodCode`)and a method of `RCObject`, in Ubuntu 18.04/sip 4.19.15, we get two different values for `this` in both methods. In Ubuntu 20.04/sip 4.19.21, we get the same value (the one of the `AWindow3D` part), and the methods of `RCObject` are using a wrong pointer.
**So I strongly suspect another bug in sip 4.19.21.**

**Comment by denisri** [comment]
I can't reproduce the problem in an isolated example. I have built a complete inheritance graph matching the `AWindow3D`'s but can't make it fail when it's not a real `AWindow3D`. Thus it's even more subtle then that...

**Comment by denisri** [comment]
Anyway it's not a refcount problem as I thought initially. I'll change the ticket title.

**Comment by denisri** [comment]
Installing the latest version of sip (4.19.25) and PyQt (5.15.5) does not solve the problem.

**Comment by denisri** [comment]
Installing an older sip 4.19.15 and PyQt 5.12.1 (same as we use on Ubuntu 18.04) actually **solves the problem**, so there has really been a behaviour change between sip 4.19.15 and 4.19.21, and this behaviour is still present in 4.19.25. The problem is that I cannot determine exactly where for now.
For now we could install and use this downgraded version, but we have to find a fix for the future...

**Comment by denisri** [comment]
Now using the same sip/PyQt as for the ununtu 18.04 image (sip 4.19.15 / PyQt 5.12.1), the `AWindow` problem is avoided, but I get hundreds of errors in `brainvisa` when loading processes:
```
   Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 5936, in readProcess
        processModule = imp.load_module(
      File "/usr/lib/python3.8/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.8/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 702, in _load
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/morphologist/processes/morphologist-ui_database.py", line 16, in <module>
        signature = Signature(
    TypeError: 'QCborKnownTags' object is not callable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 6365, in addDir
        readProcess(ff, category=category,
      File "/casa/host/build/python/brainvisa/processes.py", line 5949, in readProcess
        six.reraise(type(e),
      File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
        raise value.with_traceback(tb)
      File "/casa/host/build/python/brainvisa/processes.py", line 5936, in readProcess
        processModule = imp.load_module(
      File "/usr/lib/python3.8/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.8/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 702, in _load
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/morphologist/processes/morphologist-ui_database.py", line 16, in <module>
        signature = Signature(
    TypeError: /casa/host/build/brainvisa/toolboxes/morphologist/processes/morphologist-ui_database.py: 'QCborKnownTags' object is not callable
```
then no process is loaded at all at the end.

I don't understand where this error comes from. Looking on the web I only find this:
https://github.com/Electron-Cash/Electron-Cash/issues/1157

it seems there is a confusion between python `decimal.Decimal` function and PyQt `QtCore.Decimal` enum value (part of the `QCborKnownTags` enum), but I don't understand where it is triggered, I see no use of `Decimal` as a global variable in brainvisa code, and the tracebacks at process import are incomplete, just showing the process `signature = Signature(...)` line, not the actual use of `Decimal`.

Moreover I don't understand why this used to work (in ubuntu 18 with same PyQt, and in ubuntu 20 using a newer PyQt) and does not any longer.

I've spent almost 2 days digging into a series of messes and finding no good solution... I think we're not ready at all for Ubuintu 20.04...

**Comment by denisri** [comment]
In Ubuntu 18.04, Qt 5.9 didin't include the Decimal value, thus was not present in PyQt (even in PyQt 5.12). This explains why we didn't get trouble in ubuntu 18.04. It doesn't explain why we don't have the same problem in Ubuntu 20.04 using PyQt 5.14.

**Comment by denisri** [comment]
The Decimal problem can be avoided by removing `import *` from Qt, especially in axon `neuroProcessesGUI.py` (brainvisa/axon@eebce1235dfec743d718e1144add627177d73b31), but a number of processes still do it - anyway brainvisa itself runs this way.
However using the same sip/pyqt as in Ubuntu 18.04 does not solve #286.

**Comment by denisri** [comment]
Images 5.1 (ubuntu 20.04) have moved to 5.2 because of the numerous issues with this system - 5.1 will become a python3 variant of 5.0 (ubuntu 18.04). Thus this ticket now concerns images 5.2.

**Comment by denisri** [comment]
After some work I could build a "small" code example which exhibits the problem, and sent it to the Sip/PyQt maintainer.
