### ISSUE TITLE
Can't do the command 'singularity run -c - B ...' on /neurospin/cati

### ISSUE THREAD

**Issue by clarafischer** [brainvisa/casa-distro#334]
I tried to reinstall a brainvisa with a recent image (5.3-15) on /neurospin/cati, I already have one with an old image so it worked before or I forgot that I had to do something, but right now at the end of the command : 
`singularity run -c -B /neurospin/cati/casa_distro/brainvisa-cati_platform-master:/casa/setup /neurospin/cati/casa_distro/casa-dev-5.3-15.sif branch=master distro=cati_platform`
I have an error, if a put the .sif on my /volatile it does the same but if I do all the install on the /volatile it works without problem.

Any idea what should I do ? Thanks !

```
Traceback (most recent call last):
  File "/casa/casa-distro/python/casa_distro/environment.py", line 101, in copytree
    shutil.copystat(src, dst)
  File "/usr/lib/python3.10/shutil.py", line 378, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib/python3.10/shutil.py", line 328, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/casa/setup/cati/qualicati/database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/casa/casa-distro/cbin/casa_container", line 35, in <module>
    main(meant_for_container=True)
  File "/casa/casa-distro/python/casa_distro/command.py", line 360, in main
    result = command(*args, **kwargs)
  File "/casa/casa-distro/python/casa_distro/container_commands.py", line 85, in setup_dev
    env_setup_dev(dir, distro=distro, branch=branch, system=system,
  File "/casa/casa-distro/python/casa_distro/container_environment.py", line 365, in setup_dev
    copytree(fp, osp.join(setup_dir, i))
  File "/casa/casa-distro/python/casa_distro/environment.py", line 90, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/casa/casa-distro/python/casa_distro/environment.py", line 90, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/casa/casa-distro/python/casa_distro/environment.py", line 103, in copytree
    if (shutil.WindowsError is not None
AttributeError: module 'shutil' has no attribute 'WindowsError'
```

**Comment by sapetnioc** [comment]
The source of the problem is on the filesystem: `PermissionError: [Errno 13] Permission denied: '/casa/setup/cati/qualicati/database'`. This error raises another error because of a piece of code that, I guess, is only working on windows. We never saw this yet because file system errors are uncommon.

I will remove the Windows specific code. This will only be included in next images. But, even with a new image, you have to fix the reason of the initial permission error to fix things for you.
